import { StepConfig } from '@/types';

// XP rewards per step (gamification)
export const STEP_XP = [100, 150, 120, 100, 80] as const;
export const TOTAL_XP = STEP_XP.reduce((a, b) => a + b, 0);

export const LEVEL_NAMES = [
  'Health Rookie',
  'Wellness Explorer',
  'Nutrition Seeker',
  'Vitality Champion',
  'Wellness Master',
] as const;

export const STEP_CELEBRATIONS = [
  '🎉 Great start! Your basics are locked in.',
  '💪 Awesome! Now I know what to watch out for.',
  '🍽️ Perfect! Your food personality is clear.',
  '🌍 Nice! I can tailor this to your world.',
  '🔥 All done! Building your plan now...',
] as const;

export const STEPS: StepConfig[] = [
  {
    id: 'basics',
    title: 'About You',
    icon: 'User',
    description: 'Quick basics to get started.',
    questions: [
      {
        id: 'sex',
        question: 'What best describes you?',
        whyWeAsk: '',
        inputType: 'cards',
        options: [
          { id: 'male', label: 'Male', icon: '👨' },
          { id: 'female', label: 'Female', icon: '👩' },
          { id: 'other', label: 'Other', icon: '🧑' },
        ],
        required: true,
        fieldPath: 'body.sex',
      },
      {
        id: 'age',
        question: 'How old are you?',
        whyWeAsk: '',
        inputType: 'chips',
        options: [
          { id: '16-24', label: '16-24' },
          { id: '25-34', label: '25-34' },
          { id: '35-44', label: '35-44' },
          { id: '45-54', label: '45-54' },
          { id: '55+', label: '55+' },
        ],
        required: true,
        fieldPath: 'body.age',
      },
      {
        id: 'height',
        question: 'Height?',
        whyWeAsk: '',
        inputType: 'chips',
        options: [
          { id: 'under-150', label: '< 150 cm' },
          { id: '150-160', label: '150-160 cm' },
          { id: '160-170', label: '160-170 cm' },
          { id: '170-180', label: '170-180 cm' },
          { id: '180+', label: '180+ cm' },
        ],
        required: true,
        fieldPath: 'body.heightCm',
      },
      {
        id: 'weight',
        question: 'Current weight?',
        whyWeAsk: '',
        inputType: 'chips',
        options: [
          { id: 'under-50', label: '< 50 kg' },
          { id: '50-65', label: '50-65 kg' },
          { id: '65-80', label: '65-80 kg' },
          { id: '80-100', label: '80-100 kg' },
          { id: '100+', label: '100+ kg' },
        ],
        required: true,
        fieldPath: 'body.weightKg',
      },
      {
        id: 'activityLevel',
        question: 'How active are you?',
        whyWeAsk: '',
        inputType: 'cards',
        options: [
          { id: 'sedentary', label: 'Couch Potato', icon: '🛋️', description: 'Mostly sitting' },
          { id: 'light', label: 'Light Mover', icon: '🚶', description: 'Walk / light exercise' },
          { id: 'moderate', label: 'Active', icon: '🏃', description: 'Regular workouts' },
          { id: 'very-active', label: 'Beast Mode', icon: '🔥', description: 'Intense daily training' },
        ],
        required: true,
        fieldPath: 'body.activityLevel',
      },
      {
        id: 'primaryGoal',
        question: 'What\'s your #1 goal?',
        whyWeAsk: '',
        inputType: 'cards',
        options: [
          { id: 'weight-loss', label: 'Lose Weight', icon: '⬇️' },
          { id: 'muscle-gain', label: 'Build Muscle', icon: '💪' },
          { id: 'energy', label: 'More Energy', icon: '⚡' },
          { id: 'condition', label: 'Health Condition', icon: '🏥' },
          { id: 'maintain', label: 'Stay Healthy', icon: '✨' },
          { id: 'performance', label: 'Performance', icon: '🏆' },
        ],
        required: true,
        fieldPath: 'goals.primaryGoal',
      },
    ],
  },
  {
    id: 'health',
    title: 'Health Check',
    icon: 'HeartPulse',
    description: 'So we keep you safe.',
    questions: [
      {
        id: 'conditions',
        question: 'Any health conditions? (tap all that apply)',
        whyWeAsk: '',
        inputType: 'multi-select',
        options: [
          { id: 'none', label: 'None 🎉' },
          { id: 'diabetes', label: 'Diabetes' },
          { id: 'hypertension', label: 'High BP' },
          { id: 'pcos', label: 'PCOS' },
          { id: 'thyroid', label: 'Thyroid' },
          { id: 'ibs', label: 'IBS / Gut Issues' },
          { id: 'heart', label: 'Heart Disease' },
          { id: 'cholesterol', label: 'High Cholesterol' },
        ],
        required: true,
        fieldPath: 'medical.conditions',
        allowCustom: true,
      },
      {
        id: 'allergies',
        question: 'Food allergies? (tap all that apply)',
        whyWeAsk: '',
        inputType: 'multi-select',
        options: [
          { id: 'none', label: 'None 🎉' },
          { id: 'gluten', label: 'Gluten' },
          { id: 'dairy', label: 'Dairy' },
          { id: 'nuts', label: 'Nuts' },
          { id: 'soy', label: 'Soy' },
          { id: 'shellfish', label: 'Shellfish' },
          { id: 'eggs', label: 'Eggs' },
        ],
        required: true,
        fieldPath: 'medical.allergies',
        allowCustom: true,
      },
      {
        id: 'medications',
        question: 'On any medications?',
        whyWeAsk: '',
        inputType: 'chips',
        options: [
          { id: 'none', label: 'None' },
          { id: 'metformin', label: 'Metformin' },
          { id: 'thyroid-meds', label: 'Thyroid Meds' },
          { id: 'blood-thinners', label: 'Blood Thinners' },
          { id: 'bp-meds', label: 'BP Medication' },
          { id: 'statins', label: 'Statins' },
        ],
        required: true,
        fieldPath: 'medical.medications',
        allowCustom: true,
      },
    ],
  },
  {
    id: 'food',
    title: 'Food Vibes',
    icon: 'UtensilsCrossed',
    description: 'What you eat and love.',
    questions: [
      {
        id: 'dietType',
        question: 'What do you eat?',
        whyWeAsk: '',
        inputType: 'cards',
        options: [
          { id: 'omnivore', label: 'Everything', icon: '🥩' },
          { id: 'vegetarian', label: 'Vegetarian', icon: '🥬' },
          { id: 'vegan', label: 'Vegan', icon: '🌱' },
          { id: 'eggetarian', label: 'Eggetarian', icon: '🥚' },
          { id: 'pescatarian', label: 'Pescatarian', icon: '🐟' },
        ],
        required: true,
        fieldPath: 'dietary.dietType',
      },
      {
        id: 'cuisine',
        question: 'Pick your favorite cuisines',
        whyWeAsk: '',
        inputType: 'multi-select',
        options: [
          { id: 'indian', label: '🇮🇳 Indian' },
          { id: 'chinese', label: '🇨🇳 Chinese' },
          { id: 'italian', label: '🇮🇹 Italian' },
          { id: 'mexican', label: '🇲🇽 Mexican' },
          { id: 'japanese', label: '🇯🇵 Japanese' },
          { id: 'mediterranean', label: '🫒 Mediterranean' },
          { id: 'american', label: '🇺🇸 American' },
          { id: 'thai', label: '🇹🇭 Thai' },
          { id: 'middle-eastern', label: '🧆 Middle Eastern' },
          { id: 'korean', label: '🇰🇷 Korean' },
        ],
        required: true,
        fieldPath: 'dietary.foodsLiked',
      },
      {
        id: 'avoidFoods',
        question: 'Any foods you hate?',
        whyWeAsk: '',
        inputType: 'multi-select',
        options: [
          { id: 'none', label: 'I eat everything! 😋' },
          { id: 'bitter-gourd', label: 'Bitter Gourd' },
          { id: 'broccoli', label: 'Broccoli' },
          { id: 'tofu', label: 'Tofu' },
          { id: 'fish', label: 'Fish' },
          { id: 'mushroom', label: 'Mushrooms' },
          { id: 'okra', label: 'Okra / Lady Finger' },
          { id: 'liver', label: 'Organ Meat' },
        ],
        required: true,
        fieldPath: 'dietary.foodsDisliked',
        allowCustom: true,
      },
      {
        id: 'cookingSkill',
        question: 'Cooking level?',
        whyWeAsk: '',
        inputType: 'cards',
        options: [
          { id: 'none', label: 'Can\'t Cook', icon: '🆘', description: 'Need simple / no-cook options' },
          { id: 'beginner', label: 'Basics', icon: '🍳', description: 'Eggs, rice, simple stuff' },
          { id: 'intermediate', label: 'Decent', icon: '👨‍🍳', description: 'Can follow recipes' },
          { id: 'advanced', label: 'Chef Mode', icon: '⭐', description: 'Bring it on!' },
        ],
        required: true,
        fieldPath: 'dietary.cookingSkill',
      },
    ],
  },
  {
    id: 'lifestyle',
    title: 'Your World',
    icon: 'Globe',
    description: 'Where and how you live.',
    questions: [
      {
        id: 'location',
        question: 'Where do you live?',
        whyWeAsk: '',
        inputType: 'chips',
        options: [
          { id: 'india', label: '🇮🇳 India' },
          { id: 'usa', label: '🇺🇸 USA' },
          { id: 'uk', label: '🇬🇧 UK' },
          { id: 'uae', label: '🇦🇪 UAE' },
          { id: 'canada', label: '🇨🇦 Canada' },
          { id: 'australia', label: '🇦🇺 Australia' },
          { id: 'europe', label: '🇪🇺 Europe' },
          { id: 'sea', label: '🌏 SE Asia' },
        ],
        required: true,
        fieldPath: 'geographic.location',
        allowCustom: true,
      },
      {
        id: 'city',
        question: 'Which city or town?',
        whyWeAsk: 'So we only suggest ingredients available near you',
        inputType: 'text',
        placeholder: 'e.g. Indore, Lucknow, Jaipur...',
        required: true,
        fieldPath: 'geographic.city',
      },
      {
        id: 'budget',
        question: 'Food budget vibe?',
        whyWeAsk: '',
        inputType: 'cards',
        options: [
          { id: 'tight', label: 'Budget-Friendly', icon: '💰', description: 'Keep it affordable' },
          { id: 'moderate', label: 'Moderate', icon: '💵', description: 'Some flexibility' },
          { id: 'flexible', label: 'No Limit', icon: '💎', description: 'Quality over price' },
        ],
        required: true,
        fieldPath: 'geographic.monthlyBudget',
      },
      {
        id: 'eatingOut',
        question: 'How often do you eat out?',
        whyWeAsk: '',
        inputType: 'chips',
        options: [
          { id: 'rarely', label: 'Rarely 🏠' },
          { id: '1-2', label: '1-2x/week 🍽️' },
          { id: '3-5', label: '3-5x/week 🍜' },
          { id: 'daily', label: 'Almost daily 🚀' },
        ],
        required: true,
        fieldPath: 'geographic.eatingOutFrequency',
      },
      {
        id: 'schedule',
        question: 'What\'s your daily schedule like?',
        whyWeAsk: '',
        inputType: 'cards',
        options: [
          { id: 'early-bird', label: 'Early Bird', icon: '🌅', description: 'Up by 6, sleep by 10' },
          { id: 'nine-to-five', label: '9 to 5', icon: '💼', description: 'Regular office hours' },
          { id: 'night-owl', label: 'Night Owl', icon: '🦉', description: 'Late nights, late mornings' },
          { id: 'shift-work', label: 'Shift Work', icon: '🔄', description: 'Irregular hours' },
        ],
        required: true,
        fieldPath: 'lifestyle.dailyRoutine',
      },
      {
        id: 'stressLevel',
        question: 'Stress level?',
        whyWeAsk: '',
        inputType: 'cards',
        options: [
          { id: 'low', label: 'Chill', icon: '😌', description: 'Life is good' },
          { id: 'moderate', label: 'Some Stress', icon: '😐', description: 'Managing it' },
          { id: 'high', label: 'Stressed', icon: '😰', description: 'It\'s a lot' },
          { id: 'extreme', label: 'Burnout', icon: '🤯', description: 'Need help' },
        ],
        required: true,
        fieldPath: 'lifestyle.stressLevel',
      },
    ],
  },
  {
    id: 'final',
    title: 'Last Touches',
    icon: 'Sparkles',
    description: 'Almost there!',
    questions: [
      {
        id: 'timeline',
        question: 'How soon do you want results?',
        whyWeAsk: '',
        inputType: 'chips',
        options: [
          { id: '1-month', label: '1 month 🚀' },
          { id: '3-months', label: '3 months 📈' },
          { id: '6-months', label: '6 months 🎯' },
          { id: 'ongoing', label: 'Lifestyle change 🌱' },
        ],
        required: true,
        fieldPath: 'goals.timeline',
      },
      {
        id: 'mealPrepTime',
        question: 'Time for cooking per meal?',
        whyWeAsk: '',
        inputType: 'chips',
        options: [
          { id: 'none', label: 'Zero 🙈' },
          { id: 'minimal', label: '< 15 min ⚡' },
          { id: 'moderate', label: '15-30 min 🍳' },
          { id: 'plenty', label: '30+ min 👨‍🍳' },
        ],
        required: true,
        fieldPath: 'dietary.mealPrepTime',
      },
      {
        id: 'habits',
        question: 'Any of these apply? (tap all)',
        whyWeAsk: '',
        inputType: 'multi-select',
        options: [
          { id: 'none', label: 'None of these' },
          { id: 'snacker', label: 'Frequent Snacker 🍪' },
          { id: 'poor-sleep', label: 'Poor Sleep 😴' },
          { id: 'caffeine', label: 'Caffeine Addict ☕' },
          { id: 'alcohol', label: 'Drink Alcohol 🍷' },
          { id: 'skip-meals', label: 'Skip Meals ⏭️' },
          { id: 'emotional-eater', label: 'Emotional Eater 😢' },
          { id: 'low-water', label: 'Low Water Intake 💧' },
        ],
        required: true,
        fieldPath: 'lifestyle.habits',
      },
    ],
  },
];
